//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NM.Web.WebApplication.Timesheets.United.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasterUserRole
    {
        public int MasterUserID { get; set; }
        public int RoleID { get; set; }
    
        public virtual tblMasterUser tblMasterUser { get; set; }
    }
}
