//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NM.Web.WebApplication.Timesheets.United.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTSCompanyCode
    {
        public int CompanyCodeID { get; set; }
        public string txtCompanyCode { get; set; }
        public string txtCompanyName { get; set; }
        public string txtCompanyStatus { get; set; }
        public string txtCompanyWebsite { get; set; }
        public string txtCompanyAbbreviation { get; set; }
        public Nullable<short> chkTimesheetSystem { get; set; }
        public string txtNewCompanyIdentifier { get; set; }
    }
}
