//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NM.Web.WebApplication.Timesheets.United.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTSTimesheetHour
    {
        public int TimesheetHoursID { get; set; }
        public int EmployeeInfoId { get; set; }
        public int PayPeriodID { get; set; }
        public Nullable<int> ProcessedPayPeriod { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> TimeStart { get; set; }
        public Nullable<int> TimeEnd { get; set; }
        public decimal Hours { get; set; }
        public int HoursTypeID { get; set; }
        public Nullable<decimal> HoursRegular { get; set; }
        public Nullable<decimal> HoursHoliday { get; set; }
        public Nullable<decimal> HoursPTO { get; set; }
        public Nullable<decimal> HoursJuryDuty { get; set; }
        public Nullable<decimal> HoursBereavement { get; set; }
        public Nullable<decimal> HoursUnpaid { get; set; }
        public Nullable<decimal> HoursVolunteerPTO { get; set; }
        public Nullable<bool> OnCall { get; set; }
        public Nullable<double> Mileage { get; set; }
        public Nullable<decimal> Parking { get; set; }
        public Nullable<int> StatusTypeId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int EntryUser { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<int> SubmitUser { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<int> ApproveUser { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<int> ProcessPayPeriod { get; set; }
        public bool LockOutEmployee { get; set; }
        public bool LockOutManager { get; set; }
        public bool LockOutAll { get; set; }
    
        public virtual tblTSEmployeeInfo tblTSEmployeeInfo { get; set; }
        public virtual tblTSPayPeriod tblTSPayPeriod { get; set; }
        public virtual tblTSStatusType tblTSStatusType { get; set; }
        public virtual tblTSHoursType tblTSHoursType { get; set; }
    }
}
