//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NM.Web.WebApplication.Timesheets.United.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTSEmployeeInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTSEmployeeInfo()
        {
            this.tblTSTimesheetHours = new HashSet<tblTSTimesheetHour>();
        }
    
        public int EmployeeInfoId { get; set; }
        public Nullable<int> MasterUserID { get; set; }
        public int CompanyCodeId { get; set; }
        public int intEmployeeId { get; set; }
        public Nullable<bool> HRBP { get; set; }
        public Nullable<bool> IsNewPosition { get; set; }
        public Nullable<int> ReplacingMasterUserId { get; set; }
        public Nullable<System.DateTime> DateOfWelcomeEmail { get; set; }
        public Nullable<System.DateTime> DateOfNewHireFormSent { get; set; }
        public Nullable<System.DateTime> DateOfEnteredInPayForce { get; set; }
        public Nullable<System.DateTime> DateOfTimeSaverReminder { get; set; }
        public Nullable<System.DateTime> DateOfBackgroundCheck { get; set; }
        public Nullable<System.DateTime> DateOfEVerify { get; set; }
        public Nullable<System.DateTime> DatePopcornSent { get; set; }
        public Nullable<int> WorkStateID { get; set; }
        public string ReasonForTermination { get; set; }
        public string SpecialPayIssues { get; set; }
        public Nullable<bool> IsLetterReceived { get; set; }
        public Nullable<bool> IsNopaReceived { get; set; }
        public Nullable<System.DateTime> DateOfEmailSentToTechOps { get; set; }
        public Nullable<System.DateTime> DateOfExitInterview { get; set; }
        public Nullable<System.DateTime> DateOfInformationToPayroll { get; set; }
        public Nullable<System.DateTime> DateOfPTOPayout { get; set; }
        public Nullable<bool> IsNonDisputeUnemployment { get; set; }
        public Nullable<short> chkBenefitEligible { get; set; }
        public Nullable<short> chkPhotoShowExternal { get; set; }
        public Nullable<short> chkPhotoShowInternal { get; set; }
        public string intHRSupervisor { get; set; }
        public string memBiography { get; set; }
        public string memHRDelegate { get; set; }
        public Nullable<double> realFTE { get; set; }
        public Nullable<double> realMaxTimeOffPerWeek { get; set; }
        public string txtDomain { get; set; }
        public string txtNewOrRehire { get; set; }
        public string txtOfficer { get; set; }
        public string txtPhotoHighResolution { get; set; }
        public string txtPhotoWeb { get; set; }
        public Nullable<bool> IsNonExempt { get; set; }
        public string txtUserID { get; set; }
        public string txtUserIDFics { get; set; }
        public string txtAutograph { get; set; }
        public Nullable<int> FileNumber { get; set; }
        public Nullable<double> realHoursPerWeek { get; set; }
        public string memTemp { get; set; }
        public string memTemp2 { get; set; }
        public Nullable<short> chkProcessAsNewEmployee { get; set; }
        public Nullable<short> chkPositionChange { get; set; }
        public Nullable<short> chkTimesheetAdmin { get; set; }
        public Nullable<System.DateTime> dtmTempStartDate { get; set; }
        public string txtEmploymentType { get; set; }
        public string txtNewEmployeeIdentifier { get; set; }
        public string ManagerComments { get; set; }
        public string ITComments { get; set; }
        public string PhysicalLocation { get; set; }
        public Nullable<int> PreviousExperience { get; set; }
        public Nullable<System.Guid> TemplateId { get; set; }
        public Nullable<System.Guid> ComputerSetupId { get; set; }
        public System.DateTime AutoAudit_CreatedDate { get; set; }
        public string AutoAudit_CreatedBy { get; set; }
        public System.DateTime AutoAudit_ModifiedDate { get; set; }
        public string AutoAudit_ModifiedBy { get; set; }
        public Nullable<int> AutoAudit_RowVersion { get; set; }
        public Nullable<System.Guid> AccountSetupId { get; set; }
        public string PhonePassCode { get; set; }
        public Nullable<bool> BenefitEligible { get; set; }
        public Nullable<bool> TimesheetAdmin { get; set; }
        public Nullable<System.Guid> EmployeeTerminationid { get; set; }
        public Nullable<bool> UploadToExternalWebSite { get; set; }
        public Nullable<bool> Freddie_Mac_Signatory { get; set; }
    
        public virtual tblIndividual tblIndividual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTSTimesheetHour> tblTSTimesheetHours { get; set; }
    }
}
